---
- name: playbook to provision most of the Moodle Client Run
  hosts: all
  vars:
    ansible_user: 'root'
  become: 'true'

  vars_files:
    - default.config.yml

  pre_tasks:
    - debug:
        msg: 'Beginning of build: {{ lookup("pipe", "date +%Y-%m-%dT%H:%M:%S%z") }}'

    - name: set fact with build start timestamp
      set_fact:
        build_start: '{{ lookup("pipe", "date +%s") }}'

    - name: include customised variables
      include_vars: '{{ item }}'
      with_fileglob:
        - config.yml

  post_tasks:
    - debug:
        msg:
          - 'End of build: {{ lookup("pipe", "date +%Y-%m-%dT%H:%M:%S%z") }}'
          - 'Build duration: {{ lookup("pipe", "date +%s")|int - build_start|int }} s'

  roles:


# Client packages are as follows
     - packages
     - installjmeter
     - preparingtests
     - resetdbxx
     - runtestXX
     - resetdbss
     - runtestSS
     - resetdbss
     - runtestSM
     - resetdbmm
     - runtestM3
     - resetdbmm
     - runtestM4
     - resetdbmm
     - runtestM5
     - resetdbmm
     - runtestM6
     - resetdbmm
     - runtestM7
     - resetdbmm
     - runtestM8
     - resetdbmm   
     - runtestM9
     - resetdbmm
     - runtestMM

