---
# Wait for the specified time before running new tests
  
- name: sleep for {{sleep}} more, before moving to next test
  shell: 'sleep {{sleep}}'
  async: 500
  poll: 50
  
- name: Delete temporary java files inside ~/jmetertests/
  shell: 'rm -rf ~/jmetertests/java_pid*hprof'
  async: 30
  poll: 3
  become: yes
  become_user: "{{client_username}}"
